[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'FRAME pallet template for defining custom runtime logic.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'pallet-ocw'
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
parking_lot = "0.11.1"
frame-support = { version = "3.0.0", default-features = false, path = "../../../frame/support" }
frame-system = { version = "3.0.0", default-features = false, path = "../../../frame/system" }

sp-core = { version = "3.0.0", default-features = false,  path = "../../../primitives/core" }
sp-io = { version = "3.0.0", default-features = false, path = "../../../primitives/io" }
sp-runtime = {  version = '3.0.0', default-features = false, path = "../../../primitives/runtime" }
sp-std = { version = "3.0.0", default-features = false, path = "../../../primitives/std" }
lite-json = { version = "0.1", default-features = false }
serde = { version = "1.0.101", default-features = false, features = ["derive"] }

[dev-dependencies]
sp-core = { version = "3.0.0", default-features = false, path = "../../../primitives/core" }
sp-io = { version = "3.0.0", default-features = false, path = "../../../primitives/io" }
sp-runtime = {  version = '3.0.0', default-features = false, path = "../../../primitives/runtime" }
#serde = { version = "1.0.119" }
serde = { version = "1.0.101", default-features = false, features = ["derive"] }
sp-keystore = { version = "0.9.0", default-features = false,  path = "../../../primitives/keystore" }


[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    "sp-core/std",
    "sp-std/std",
]
